name: Build
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_call:

permissions:
    contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build src\DurangoInteropDotnet.csproj -property:Configuration=Release
    - name: Copy README and LICENSE
      run: |
        copy README.md src\bin\Release\net8.0-windows\
        copy LICENSE src\bin\Release\net8.0-windows\
    - name: Upload artifacts
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-release-artifacts
        path: src/bin/Release/net8.0-windows/**

  release:
    needs: build
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: win-release-artifacts
    - name: List files
      run: ls -R .
    - name: Package
      shell: bash
      run: |
        7z a -tzip "DurangoInterop_${{ github.ref_name }}.zip" "*"
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: "DurangoInterop_${{ github.ref_name }}.zip"
        make_latest: true
        generate_release_notes: true
        fail_on_unmatched_files: true