name: Build
on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK 8.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build src\DurangoInteropDotnet.csproj -property:Configuration=Release
    - name: Upload artifacts
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-release-artifacts
        path: src/bin/Release/net8.0-windows/**
